export const authError = {
  ERR_1: "USERNAME NOT FOUND",
  ERR_2: "INCORRECT PASSWORD",
  ERR_3: "NO REFRESH TOKEN IN COOKIE",
  ERR_4: "NO REFRESH TOKEN PRESENT IN DB OR NOT MATCHED",
  ERR_5: "THERE IS SOMETHING WRONG WITH REFESH TOKEN",
  ERR_6: "TOKEN IS NOT MATCHED",
  ERR_7: "INVALID LINK!",
};
export const authSuc = {
  SUC_1: "ACCOUNT SUCCESSFULLY CREATED",
  SUC_2: "LOGGED IN SUCCESSFULLY",
  SUC_3: "GET ACCESSTOKEN SUCCESSFULLY",
  SUC_4: "PASSWORD SUCCESSFULLY CHANGED",
  SUC_5: "CHECK TOKEN VERIFY SUCCESSFULLY",
  SUC_6: "CHECK TOKEN RESET PASSWORD SUCCESSFULLY",
};
export const productSuc = {
  SUC_1: "PRODUCT SUCCESSFULLY CREATED",
  SUC_2: "GET ALL PRODUCT SUCCESSFULLY",
  SUC_3: "GET PRODUCT SUCCESSFULLY",
  SUC_4: "PRODUCT SUCCESSFULLY DELETED",
  SUC_5: "PRODUCT SUCCESSFULLY UPDATED",
};
export const productErr = {
  ERR_1: "PRODUCT NOT FOUND",
  ERR_2: "CREATE PRODUCT FAILED",
  ERR_3: "UPDATE PRODUCT FAILED",
  ERR_4: "DELETE PRODUCT FAILED",
};
export const categorySuc = {
  SUC_1: "CATEGORY SUCCESSFULLY CREATED",
  SUC_2: "GET ALL CATEGORY SUCCESSFULLY",
  SUC_3: "CATEGORY SUCCESSFULLY UPDATED",
  SUC_4: "CATEGORY SUCCESSFULLY DELETED",
};
export const categoryErr = {
  ERR_1: "CREATE CATEGORY FAILED",
  ERR_2: "CATEGORY NOT FOUND ",
};
export const brandSuc = {
  SUC_1: "BRAND SUCCESSFULLY CREATED",
  SUC_2: "GET ALL BRAND SUCCESSFULLY",
  SUC_3: "BRAND SUCCESSFULLY UPDATED",
  SUC_4: "BRAND SUCCESSFULLY DELETED",
};
export const brandErr = {
  ERR_1: "CREATE BRAND FAILED",
  ERR_2: "BRAND NOT FOUND",
  ERR_3: "DELETE BRAND FAILED",
};
export const userSuc = {
  SUC_1: "USER SUCCESSFULLY CREATED",
  SUC_2: "GET ALL USER SUCCESSFULLY",
  SUC_3: "GET USER BY ID SUCCESSFULLY",
  SUC_4: " USER BY ID SUCCESSFULLY UPDATED",
  SUC_5: "USER BY ID SUCCESSFULLY DELETED",
};
export const userErr = {
  ERR_1: "CREATE USER FAILED",
  ERR_2: "GET ALL USER FAILED",
  ERR_3: "GET USER BY ID FAILED",
  ERR_4: "UPDATE USER BY ID FAILTED",
  ERR_5: "DELETE USER BY ID FAILTED",
};
export const orderSuc = {
  SUC_1: "ORDER SUCCESSFULLY CREATED",
  SUC_2: "GET ALL ORDER SUCCESSFULLY",
  SUC_3: "GET ORDER BY ID SUCCESSFULLY",
  SUC_4: " ORDER BY ID SUCCESSFULLY UPDATED",
  SUC_5: "ORDER BY ID SUCCESSFULLY DELETED",
};
export const orderErr = {
  ERR_1: "CREATE ORDER FAILED",
  ERR_2: "GET ALL ORDER FAILED",
  ERR_3: "GET ORDER BY ID FAILED",
  ERR_4: "UPDATE ORDER BY ID FAILTED",
  ERR_5: "DELETE ORDER BY ID FAILTED",
};
export const couponSuc = {
  SUC_1: "COUPON SUCCESSFULLY CREATED",
  SUC_2: "GET ALL COUPON SUCCESSFULLY",
  SUC_3: "GET COUPON BY ID SUCCESSFULLY",
  SUC_4: " COUPON BY ID SUCCESSFULLY UPDATED",
  SUC_5: "COUPON BY ID SUCCESSFULLY DELETED",
};
export const couponErr = {
  ERR_1: "CREATE COUPON FAILED",
  ERR_2: "GET ALL COUPON FAILED",
  ERR_3: "GET COUPON BY ID FAILED",
  ERR_4: "UPDATE COUPON BY ID FAILTED",
  ERR_5: "DELETE COUPON BY ID FAILTED",
  ERR_6: "COUPON NOT FOUND",
};
export const cartSuc = {
  SUC_1: "CART SUCCESSFULLY CREATED",
  SUC_2: "GET ALL CART SUCCESSFULLY",
  SUC_3: "GET CART BY ID SUCCESSFULLY",
  SUC_4: " CART BY ID SUCCESSFULLY UPDATED",
  SUC_5: "CART BY ID SUCCESSFULLY DELETED",
  SUC_6: "SUCCESSFULLY APPLIED COUPON",
};
export const cartErr = {
  ERR_1: "CREATE CART FAILED",
  ERR_2: "GET ALL CART FAILED",
  ERR_3: "GET CART BY ID FAILED",
  ERR_4: "UPDATE CART BY ID FAILTED",
  ERR_5: "DELETE CART BY ID FAILTED",
  ERR_6: "CART NOT FOUND",
};
